### ISSUE TITLE
FIO v2.0.0 required Mainnet chain update

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fio.chain#19]
## Important FIO Mainnet update

FIO has released a v2.0 upgrade to Mainnet that will cause Mainnet nodes that have not upgraded to fork off of the Mainnet chain. It is thus important for all Mainnet nodes (including signing, history, and API nodes) to upgrade to this version. 

Previous Mainnet version: v1.0.5 (https://github.com/fioprotocol/fio/releases/tag/v1.0.5)
New Mainnet version: v2.0.0 (https://github.com/fioprotocol/fio/releases/tag/v2.0.0)

### Schedule
All Mainnet nodes must be updated according to the following schedule:

- Week of August 10 - Reach out to Exchanges and Wallets to ask about upgrade timing. (Completed)
- Milestone 1 (Aug-14) - Announce release and schedule to FIO community. (Completed)
- Milestone 2 (Sep-4) - All Mainnet nodes must be upgraded to v2.0
- Milestone 3 (Sep-11) - FIP-12 system contract msig approved on mainnet. This enables the calling of addaction/remaction.
- Milestone 4 (Sep-16) **Mainnet forking transaction:** addaction msigs approved for 50-60 fio actions
- Milestone 5 (Wed Sep 23 16:00:00 UTC 2020 ) The new actions table needs to be populated with all of the allowed actions in the fio protocol. If Milestone 4 is not fully executed by this date the blockchain will reject all actions that are not in the new whitelist table.

**Comment by pawmmm** [comment]
Obsolete
